### ISSUE TITLE
Case statements KILL this

### ISSUE THREAD

**Issue by jlippiner** [mocoso/code-beautifier.tmbundle#1]
Case statements in the ruby code completely mess up the beautifier.  All lines POST the case statement end up indented.  Take a look:

<pre>
def index
    #    check to see if there any any outstanding invitations
    accept_invites if session[:invite_id]

    @projects = @current_user.projects.find(:all)
  end

  def edit
    @sidenav = "details"
    render :action => "new"
  end

  def update
    #    check to see if they are an admin and, if not, just update member stuff
    if @member.admin
      case params[:do]
                    when "update_details"
                    update_project
                    when "update_options"
                    update_options
                  end
                  else
                    flash.notice = "#{@project.name} Updated"
                    redirect_to projects_path
                  end
                  end

                  def new
                    @project = Project.new()
                    @member = Member.new({:project_tag => ""})
                    @sidenav = "details"
                    @step = "details"
                    @title = "Step 1 - Project Details"
                    render :new
                  end
</pre>

**Comment by mocoso** [comment]
The problem was with :do being identified as the start of a do block. Fixed with commit 29b047f00cc2998d6e43222474b32bc229e3fad6
