### ISSUE TITLE
Ruby comment blocks

### ISSUE THREAD

**Issue by jeroenj** [mocoso/code-beautifier.tmbundle#3]
Hi,

If found that ruby comment blocks do not seem to be supported.
If I beautify my code the "=begin" get's indented as it is a normal line of code. The "=end" remains at col 0.

Check [multiline comments here](http://ruby.about.com/od/rubyfeatures/a/comment.htm)

**Comment by mocoso** [comment]
I don't use comment blocks as a general rule so no never wrote support for it. if you wanted to write a fix I'd be glad to merge it into the project

**Comment by jeroenj** [comment]
I never use it too but I'm working on a legacy project and it breaks there. I might look into fixing it :)

**Comment by jeroenj** [comment]
Actually you've used it [here](http://github.com/mocoso/code-beautifier.tmbundle/blob/master/Support/lib/rbeautify.rb)

**Comment by mocoso** [comment]
Oops, caught in the act ;o)

**Comment by jeroenj** [comment]
Closing this as this tmbundle is no longer supported, I no longer use TextMate and [code blocks are discouraged too](https://github.com/bbatsov/ruby-style-guide#no-block-comments). :)
