### ISSUE TITLE
Duplicate file contents

### ISSUE THREAD

**Issue by az10sbum** [mocoso/code-beautifier.tmbundle#4]
In the file 'Beautify Ruby.tmCommand' the following lines cause the beautified file to be inserted after the original unbeautified file resulting in duplicating everything:
<code>&lt;key&gt;output&lt;/key&gt;
&lt;string&gt;replaceSelectedText&lt;/string&gt;</code>

If I change these lines to:
<code>&lt;key&gt;output&lt;/key&gt;
&lt;string&gt;replaceDocument&lt;/string&gt;</code>
It works as I was expecting it to.

I am not using Textmate, so perhaps there is some compatibility with my system or perhaps this is the desired behavior.

thanks for the bundle.  I like it.

**Comment by mocoso** [comment]
Well spotted, this is indeed a bug. 

Fixed in commit 31ad7b926c4639bea40672d78357f2fb3761d3c4
